version: '3.7'
services:
  nest:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mysql
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - LAUNCH_ENV=prod

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_HOST=${DB_HOST}
      - TZ=Asia/Seoul

volumes:
  mysql-data:
